import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import SideNavWrapper from '../components/side-nav'
import Header from '../components/header'
import MarginWidthWrapper from '../components/margin-width-wrapper'
import PageWrapper from '../components/page-wrapper'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`bg-white${inter.className}`}>
        <div className="flex">
          <SideNavWrapper />
          <main className="flex-1">
            <MarginWidthWrapper>
              <Header />
              <PageWrapper>{children}</PageWrapper>
            </MarginWidthWrapper>
          </main>
        </div>
      </body>
    </html>
  )
}
